/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LimsRouteImport } from './routes/lims'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LimsIndexRouteImport } from './routes/lims.index'
import { Route as LimsValidationIndexRouteImport } from './routes/lims.validation.index'
import { Route as LimsTestsIndexRouteImport } from './routes/lims.tests.index'
import { Route as LimsSamplesIndexRouteImport } from './routes/lims.samples.index'
import { Route as LimsReportsIndexRouteImport } from './routes/lims.reports.index'
import { Route as LimsPatientsIndexRouteImport } from './routes/lims.patients.index'
import { Route as LimsOrdersIndexRouteImport } from './routes/lims.orders.index'
import { Route as LimsTestsNewRouteImport } from './routes/lims.tests.new'
import { Route as LimsOrdersNewRouteImport } from './routes/lims.orders.new'
import { Route as LimsOrdersOrderIdRouteImport } from './routes/lims.orders.$orderId'
import { Route as LimsTestsPackagesNewRouteImport } from './routes/lims.tests.packages.new'
import { Route as LimsOrdersOrderIdInvoiceRouteImport } from './routes/lims.orders.$orderId.invoice'
import { Route as LimsOrdersOrderIdResultTestIdRouteImport } from './routes/lims.orders.$orderId.result.$testId'
import { Route as LimsOrdersOrderIdReportTestIdRouteImport } from './routes/lims.orders.$orderId.report.$testId'

const LimsRoute = LimsRouteImport.update({
  id: '/lims',
  path: '/lims',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LimsIndexRoute = LimsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LimsRoute,
} as any)
const LimsValidationIndexRoute = LimsValidationIndexRouteImport.update({
  id: '/validation/',
  path: '/validation/',
  getParentRoute: () => LimsRoute,
} as any)
const LimsTestsIndexRoute = LimsTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => LimsRoute,
} as any)
const LimsSamplesIndexRoute = LimsSamplesIndexRouteImport.update({
  id: '/samples/',
  path: '/samples/',
  getParentRoute: () => LimsRoute,
} as any)
const LimsReportsIndexRoute = LimsReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => LimsRoute,
} as any)
const LimsPatientsIndexRoute = LimsPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => LimsRoute,
} as any)
const LimsOrdersIndexRoute = LimsOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => LimsRoute,
} as any)
const LimsTestsNewRoute = LimsTestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => LimsRoute,
} as any)
const LimsOrdersNewRoute = LimsOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => LimsRoute,
} as any)
const LimsOrdersOrderIdRoute = LimsOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => LimsRoute,
} as any)
const LimsTestsPackagesNewRoute = LimsTestsPackagesNewRouteImport.update({
  id: '/tests/packages/new',
  path: '/tests/packages/new',
  getParentRoute: () => LimsRoute,
} as any)
const LimsOrdersOrderIdInvoiceRoute =
  LimsOrdersOrderIdInvoiceRouteImport.update({
    id: '/invoice',
    path: '/invoice',
    getParentRoute: () => LimsOrdersOrderIdRoute,
  } as any)
const LimsOrdersOrderIdResultTestIdRoute =
  LimsOrdersOrderIdResultTestIdRouteImport.update({
    id: '/result/$testId',
    path: '/result/$testId',
    getParentRoute: () => LimsOrdersOrderIdRoute,
  } as any)
const LimsOrdersOrderIdReportTestIdRoute =
  LimsOrdersOrderIdReportTestIdRouteImport.update({
    id: '/report/$testId',
    path: '/report/$testId',
    getParentRoute: () => LimsOrdersOrderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lims': typeof LimsRouteWithChildren
  '/lims/': typeof LimsIndexRoute
  '/lims/orders/$orderId': typeof LimsOrdersOrderIdRouteWithChildren
  '/lims/orders/new': typeof LimsOrdersNewRoute
  '/lims/tests/new': typeof LimsTestsNewRoute
  '/lims/orders/': typeof LimsOrdersIndexRoute
  '/lims/patients/': typeof LimsPatientsIndexRoute
  '/lims/reports/': typeof LimsReportsIndexRoute
  '/lims/samples/': typeof LimsSamplesIndexRoute
  '/lims/tests/': typeof LimsTestsIndexRoute
  '/lims/validation/': typeof LimsValidationIndexRoute
  '/lims/orders/$orderId/invoice': typeof LimsOrdersOrderIdInvoiceRoute
  '/lims/tests/packages/new': typeof LimsTestsPackagesNewRoute
  '/lims/orders/$orderId/report/$testId': typeof LimsOrdersOrderIdReportTestIdRoute
  '/lims/orders/$orderId/result/$testId': typeof LimsOrdersOrderIdResultTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lims': typeof LimsIndexRoute
  '/lims/orders/$orderId': typeof LimsOrdersOrderIdRouteWithChildren
  '/lims/orders/new': typeof LimsOrdersNewRoute
  '/lims/tests/new': typeof LimsTestsNewRoute
  '/lims/orders': typeof LimsOrdersIndexRoute
  '/lims/patients': typeof LimsPatientsIndexRoute
  '/lims/reports': typeof LimsReportsIndexRoute
  '/lims/samples': typeof LimsSamplesIndexRoute
  '/lims/tests': typeof LimsTestsIndexRoute
  '/lims/validation': typeof LimsValidationIndexRoute
  '/lims/orders/$orderId/invoice': typeof LimsOrdersOrderIdInvoiceRoute
  '/lims/tests/packages/new': typeof LimsTestsPackagesNewRoute
  '/lims/orders/$orderId/report/$testId': typeof LimsOrdersOrderIdReportTestIdRoute
  '/lims/orders/$orderId/result/$testId': typeof LimsOrdersOrderIdResultTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lims': typeof LimsRouteWithChildren
  '/lims/': typeof LimsIndexRoute
  '/lims/orders/$orderId': typeof LimsOrdersOrderIdRouteWithChildren
  '/lims/orders/new': typeof LimsOrdersNewRoute
  '/lims/tests/new': typeof LimsTestsNewRoute
  '/lims/orders/': typeof LimsOrdersIndexRoute
  '/lims/patients/': typeof LimsPatientsIndexRoute
  '/lims/reports/': typeof LimsReportsIndexRoute
  '/lims/samples/': typeof LimsSamplesIndexRoute
  '/lims/tests/': typeof LimsTestsIndexRoute
  '/lims/validation/': typeof LimsValidationIndexRoute
  '/lims/orders/$orderId/invoice': typeof LimsOrdersOrderIdInvoiceRoute
  '/lims/tests/packages/new': typeof LimsTestsPackagesNewRoute
  '/lims/orders/$orderId/report/$testId': typeof LimsOrdersOrderIdReportTestIdRoute
  '/lims/orders/$orderId/result/$testId': typeof LimsOrdersOrderIdResultTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lims'
    | '/lims/'
    | '/lims/orders/$orderId'
    | '/lims/orders/new'
    | '/lims/tests/new'
    | '/lims/orders/'
    | '/lims/patients/'
    | '/lims/reports/'
    | '/lims/samples/'
    | '/lims/tests/'
    | '/lims/validation/'
    | '/lims/orders/$orderId/invoice'
    | '/lims/tests/packages/new'
    | '/lims/orders/$orderId/report/$testId'
    | '/lims/orders/$orderId/result/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lims'
    | '/lims/orders/$orderId'
    | '/lims/orders/new'
    | '/lims/tests/new'
    | '/lims/orders'
    | '/lims/patients'
    | '/lims/reports'
    | '/lims/samples'
    | '/lims/tests'
    | '/lims/validation'
    | '/lims/orders/$orderId/invoice'
    | '/lims/tests/packages/new'
    | '/lims/orders/$orderId/report/$testId'
    | '/lims/orders/$orderId/result/$testId'
  id:
    | '__root__'
    | '/'
    | '/lims'
    | '/lims/'
    | '/lims/orders/$orderId'
    | '/lims/orders/new'
    | '/lims/tests/new'
    | '/lims/orders/'
    | '/lims/patients/'
    | '/lims/reports/'
    | '/lims/samples/'
    | '/lims/tests/'
    | '/lims/validation/'
    | '/lims/orders/$orderId/invoice'
    | '/lims/tests/packages/new'
    | '/lims/orders/$orderId/report/$testId'
    | '/lims/orders/$orderId/result/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LimsRoute: typeof LimsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lims': {
      id: '/lims'
      path: '/lims'
      fullPath: '/lims'
      preLoaderRoute: typeof LimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lims/': {
      id: '/lims/'
      path: '/'
      fullPath: '/lims/'
      preLoaderRoute: typeof LimsIndexRouteImport
      parentRoute: typeof LimsRoute
    }
    '/lims/validation/': {
      id: '/lims/validation/'
      path: '/validation'
      fullPath: '/lims/validation/'
      preLoaderRoute: typeof LimsValidationIndexRouteImport
      parentRoute: typeof LimsRoute
    }
    '/lims/tests/': {
      id: '/lims/tests/'
      path: '/tests'
      fullPath: '/lims/tests/'
      preLoaderRoute: typeof LimsTestsIndexRouteImport
      parentRoute: typeof LimsRoute
    }
    '/lims/samples/': {
      id: '/lims/samples/'
      path: '/samples'
      fullPath: '/lims/samples/'
      preLoaderRoute: typeof LimsSamplesIndexRouteImport
      parentRoute: typeof LimsRoute
    }
    '/lims/reports/': {
      id: '/lims/reports/'
      path: '/reports'
      fullPath: '/lims/reports/'
      preLoaderRoute: typeof LimsReportsIndexRouteImport
      parentRoute: typeof LimsRoute
    }
    '/lims/patients/': {
      id: '/lims/patients/'
      path: '/patients'
      fullPath: '/lims/patients/'
      preLoaderRoute: typeof LimsPatientsIndexRouteImport
      parentRoute: typeof LimsRoute
    }
    '/lims/orders/': {
      id: '/lims/orders/'
      path: '/orders'
      fullPath: '/lims/orders/'
      preLoaderRoute: typeof LimsOrdersIndexRouteImport
      parentRoute: typeof LimsRoute
    }
    '/lims/tests/new': {
      id: '/lims/tests/new'
      path: '/tests/new'
      fullPath: '/lims/tests/new'
      preLoaderRoute: typeof LimsTestsNewRouteImport
      parentRoute: typeof LimsRoute
    }
    '/lims/orders/new': {
      id: '/lims/orders/new'
      path: '/orders/new'
      fullPath: '/lims/orders/new'
      preLoaderRoute: typeof LimsOrdersNewRouteImport
      parentRoute: typeof LimsRoute
    }
    '/lims/orders/$orderId': {
      id: '/lims/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/lims/orders/$orderId'
      preLoaderRoute: typeof LimsOrdersOrderIdRouteImport
      parentRoute: typeof LimsRoute
    }
    '/lims/tests/packages/new': {
      id: '/lims/tests/packages/new'
      path: '/tests/packages/new'
      fullPath: '/lims/tests/packages/new'
      preLoaderRoute: typeof LimsTestsPackagesNewRouteImport
      parentRoute: typeof LimsRoute
    }
    '/lims/orders/$orderId/invoice': {
      id: '/lims/orders/$orderId/invoice'
      path: '/invoice'
      fullPath: '/lims/orders/$orderId/invoice'
      preLoaderRoute: typeof LimsOrdersOrderIdInvoiceRouteImport
      parentRoute: typeof LimsOrdersOrderIdRoute
    }
    '/lims/orders/$orderId/result/$testId': {
      id: '/lims/orders/$orderId/result/$testId'
      path: '/result/$testId'
      fullPath: '/lims/orders/$orderId/result/$testId'
      preLoaderRoute: typeof LimsOrdersOrderIdResultTestIdRouteImport
      parentRoute: typeof LimsOrdersOrderIdRoute
    }
    '/lims/orders/$orderId/report/$testId': {
      id: '/lims/orders/$orderId/report/$testId'
      path: '/report/$testId'
      fullPath: '/lims/orders/$orderId/report/$testId'
      preLoaderRoute: typeof LimsOrdersOrderIdReportTestIdRouteImport
      parentRoute: typeof LimsOrdersOrderIdRoute
    }
  }
}

interface LimsOrdersOrderIdRouteChildren {
  LimsOrdersOrderIdInvoiceRoute: typeof LimsOrdersOrderIdInvoiceRoute
  LimsOrdersOrderIdReportTestIdRoute: typeof LimsOrdersOrderIdReportTestIdRoute
  LimsOrdersOrderIdResultTestIdRoute: typeof LimsOrdersOrderIdResultTestIdRoute
}

const LimsOrdersOrderIdRouteChildren: LimsOrdersOrderIdRouteChildren = {
  LimsOrdersOrderIdInvoiceRoute: LimsOrdersOrderIdInvoiceRoute,
  LimsOrdersOrderIdReportTestIdRoute: LimsOrdersOrderIdReportTestIdRoute,
  LimsOrdersOrderIdResultTestIdRoute: LimsOrdersOrderIdResultTestIdRoute,
}

const LimsOrdersOrderIdRouteWithChildren =
  LimsOrdersOrderIdRoute._addFileChildren(LimsOrdersOrderIdRouteChildren)

interface LimsRouteChildren {
  LimsIndexRoute: typeof LimsIndexRoute
  LimsOrdersOrderIdRoute: typeof LimsOrdersOrderIdRouteWithChildren
  LimsOrdersNewRoute: typeof LimsOrdersNewRoute
  LimsTestsNewRoute: typeof LimsTestsNewRoute
  LimsOrdersIndexRoute: typeof LimsOrdersIndexRoute
  LimsPatientsIndexRoute: typeof LimsPatientsIndexRoute
  LimsReportsIndexRoute: typeof LimsReportsIndexRoute
  LimsSamplesIndexRoute: typeof LimsSamplesIndexRoute
  LimsTestsIndexRoute: typeof LimsTestsIndexRoute
  LimsValidationIndexRoute: typeof LimsValidationIndexRoute
  LimsTestsPackagesNewRoute: typeof LimsTestsPackagesNewRoute
}

const LimsRouteChildren: LimsRouteChildren = {
  LimsIndexRoute: LimsIndexRoute,
  LimsOrdersOrderIdRoute: LimsOrdersOrderIdRouteWithChildren,
  LimsOrdersNewRoute: LimsOrdersNewRoute,
  LimsTestsNewRoute: LimsTestsNewRoute,
  LimsOrdersIndexRoute: LimsOrdersIndexRoute,
  LimsPatientsIndexRoute: LimsPatientsIndexRoute,
  LimsReportsIndexRoute: LimsReportsIndexRoute,
  LimsSamplesIndexRoute: LimsSamplesIndexRoute,
  LimsTestsIndexRoute: LimsTestsIndexRoute,
  LimsValidationIndexRoute: LimsValidationIndexRoute,
  LimsTestsPackagesNewRoute: LimsTestsPackagesNewRoute,
}

const LimsRouteWithChildren = LimsRoute._addFileChildren(LimsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LimsRoute: LimsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
